name: Notify when a pull request is made
on:
  pull_request:
    types: [opened, closed, reopened]

jobs:
  printJob:
    name: Print event
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: |
          echo "$GITHUB_CONTEXT"
      - name: Dump event payload
        env:
          EVENT_PAYLOAD: ${{ toJson(EVENT_PAYLOAD) }}
        run: |
          echo "$EVENT_PAYLOAD"

  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Discord notification
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK_URL }}
        uses: Ilshidur/action-discord@master
        with:
          args: "A pull request to master has been opened: {{ EVENT_PAYLOAD.event.pull_request.html.href }}"
